package frames

// All contains all generated frame definitions.
var All = []*Definition{
	AmigaLike,
	AmigaLikeLarge,
	AmigaLikeXlarge,
	BeosLike,
	BeosLikeLarge,
	BeosLikeXlarge,
	Chains,
	ChainsLarge,
	ChainsXlarge,
	Checkers,
	CheckersLarge,
	CheckersXlarge,
	ChinaPattern,
	ChinaPatternLarge,
	ChinaPatternXlarge,
	Dots,
	DotsLarge,
	DotsXlarge,
	FantasyStone,
	FantasyStoneLarge,
	FantasyStoneXlarge,
	Floral,
	FloralLarge,
	FloralXlarge,
	Gold,
	GoldLarge,
	GoldXlarge,
	Hearts,
	HeartsLarge,
	HeartsXlarge,
	MacSystem3Like,
	MacSystem3LikeLarge,
	MacSystem3LikeXlarge,
	MacSystem9Like,
	MacSystem9LikeLarge,
	MacSystem9LikeXlarge,
	MacosxLike,
	MacosxLikeLarge,
	MacosxLikeXlarge,
	Metal,
	MetalLarge,
	MetalXlarge,
	MwmLike,
	MwmLikeLarge,
	MwmLikeXlarge,
	NextLike,
	NextLikeLarge,
	NextLikeXlarge,
	Rainbow,
	RainbowLarge,
	RainbowXlarge,
	Ridge,
	RidgeLarge,
	RidgeXlarge,
	ScifiTech,
	ScifiTechLarge,
	ScifiTechXlarge,
	SignConstruction,
	SignConstructionLarge,
	SignConstructionXlarge,
	SignStreet,
	SignStreetLarge,
	SignStreetRounded,
	SignStreetRoundedLarge,
	SignStreetRoundedXlarge,
	SignStreetXlarge,
	SignWarning,
	SignWarningLarge,
	SignWarningXlarge,
	Waves,
	WavesLarge,
	WavesXlarge,
	Win31Like,
	Win31LikeLarge,
	Win31LikeXlarge,
	Win95Like,
	Win95LikeLarge,
	Win95LikeXlarge,
	Win95Window,
	Win95WindowLarge,
	Win95WindowXlarge,
	WindowFuture,
	WindowFutureLarge,
	WindowFutureXlarge,
	WindowGlass,
	WindowGlassLarge,
	WindowGlassXlarge,
	WindowHouse,
	WindowHouseLarge,
	WindowHouseXlarge,
	WindowPaper,
	WindowPaperLarge,
	WindowPaperXlarge,
	WindowRetro,
	WindowRetroCloseOnly,
	WindowRetroCloseOnlyLarge,
	WindowRetroCloseOnlyXlarge,
	WindowRetroLarge,
	WindowRetroMinMaxClose,
	WindowRetroMinMaxCloseLarge,
	WindowRetroMinMaxCloseXlarge,
	WindowRetroXlarge,
	Wood,
	WoodLarge,
	WoodXlarge,
}

// ByName maps frame names to their definitions.
var ByName = map[string]*Definition{}

func init() {
	for _, d := range All {
		ByName[d.Name] = d
	}
}

// List returns a defensive copy of the All slice.
func List() []*Definition {
	ret := make([]*Definition, len(All))
	copy(ret, All)
	return ret
}
